name: Build UniGetUI (no tests)
run-name: Build UniGetUI (no tests)
on:
  workflow_dispatch:
      inputs:
        build_installer:
          description: 'Build installer'
          type: boolean
          default: true
        repository:
          description: 'Repo'
          default: 'marticliment/UniGetUI'
          required: true
          type: string
        ref:
          description: 'Branch/tag/ref'
          type: string
        verbosity:
          description: 'Build verbosity'
          required: true
          default: 'minimal'
          type: choice
          options:
            - quiet
            - minimal
            - normal
            - detailed
            - diagnostic
        win-x64:
          description: 'Build for x64'
          required: true
          type: boolean
        win-x86:
          description: 'Build for x86'
          required: true
          type: boolean
        win-arm64:
          description: 'Build for arm64'
          required: true
          default: true
          type: boolean

jobs:
  get-selected:
    runs-on: ubuntu-latest
    outputs: # Set this to consume the output on other job
      selected: ${{ steps.get-selected-step.outputs.selected }}
    steps:
      - id: get-selected-step
        uses: joao-zanutto/get-selected@v1.1.1
        with:
          ignore: build_installer
          format: json

  build:
    runs-on: windows-latest
    needs: get-selected
    strategy:
      matrix:
        architecture: ${{ fromJSON(needs.get-selected.outputs.selected) }}
    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}

      - name: Build
        run: dotnet publish src\UniGetUi\UniGetUi.csproj --configuration Release --runtime ${{ matrix.architecture }} --self-contained --verbosity ${{ inputs.verbosity }}

      - name: Upload build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: UniGetUI-build-${{ matrix.architecture }}
          path: ./src/UniGetUI/bin/**/publish
          include-hidden-files: true

  build_installer:
    if: ${{ inputs.build_installer }}
    runs-on: windows-latest
    needs: [build, get-selected]
    strategy:
      matrix:
        architecture: ${{ fromJSON(needs.get-selected.outputs.selected) }}
    steps:
      - name: Get build from other job
        uses: actions/download-artifact@v4
        with:
          name: UniGetUI-build-${{ matrix.architecture }}
          path: unigetui_bin

      - name: Show tree
        run: tree

      - name: Get UniGetUI.iss
        uses: actions/checkout@master
        with:
          sparse-checkout: UniGetUI.iss
          path: .\

      - name: Get other required assets
        uses: actions/checkout@master
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}    
          sparse-checkout: |
            InstallerExtras
            src\UniGetUI\Assets\Images

      - name: Build installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
        with:
          path: UniGetUI.iss
        
      - name: Show dir
        run: dir

      - name: Upload installer as artifact
        uses: actions/download-artifact@v4
        with:
          name: UniGetUI-Installer-${{ matrix.architecture }}
          path: "UniGetUI Installer.exe"
          include-hidden-files: true
