name: Build UniGetUI (no tests)
run-name: Build UniGetUI (no tests)
on:
  workflow_dispatch:
      inputs:
        run_id:
          description: 'Run ID containing build (Leave empty to recompile)'
          type: number
        build_installer:
          description: 'Build installer'
          type: boolean
          default: true
        repository:
          description: 'Repo'
          default: 'marticliment/UniGetUI'
          required: true
          type: string
        ref:
          description: 'Branch/tag/ref'
          type: string
        verbosity:
          description: 'Build verbosity'
          required: true
          default: 'minimal'
          type: choice
          options:
            - quiet
            - minimal
            - normal
            - detailed
            - diagnostic
        win-x64:
          description: 'Build for x64'
          required: true
          type: boolean
        win-x86:
          description: 'Build for x86'
          required: true
          type: boolean
        win-arm64:
          description: 'Build for arm64'
          required: true
          default: true
          type: boolean

jobs:
  get-selected:
    runs-on: ubuntu-latest
    outputs: # Set this to consume the output on other job
      selected: ${{ steps.get-selected-step.outputs.selected }}
    steps:
      - id: get-selected-step
        uses: joao-zanutto/get-selected@v1.1.1
        with:
          ignore: build_installer
          format: json

  build_binary:
    if: ${{ ! inputs.run_id }}
    runs-on: windows-latest
    needs: get-selected
    strategy:
      matrix:
        architecture: ${{ fromJSON(needs.get-selected.outputs.selected) }}
    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}

      - name: Build
        run: dotnet publish src\UniGetUI\UniGetUI.csproj --configuration Release --runtime ${{ matrix.architecture }} --self-contained --verbosity ${{ inputs.verbosity }}

      - name: Upload build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: UniGetUI-build-${{ matrix.architecture }}
          path: src\UniGetUI\bin\Release\net8.0-windows10.0.26100.0\${{ matrix.architecture }}\publish
          include-hidden-files: true

  build_installer:
    if: ${{ always() && inputs.build_installer && ( (inputs.run_id && needs.build_binary.result == 'skipped') || !inputs.run_id ) }}
    runs-on: windows-latest
    needs: [build_binary, get-selected]
    strategy:
      matrix:
        architecture: ${{ fromJSON(needs.get-selected.outputs.selected) }}
    steps:
      - name: Get UniGetUI.iss
        uses: actions/checkout@master
        with:
          sparse-checkout: UniGetUI.iss
          path: .\

      - name: Apply patch to disable code signing
        run: |
          tree /f
          git apply --directory=UniGetUI-arm64/UniGetUI-arm64 disable-signing.patch 

      - name: Get other required assets
        uses: actions/checkout@master
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}    
          sparse-checkout: |
            InstallerExtras
            src\UniGetUI\Assets\Images
            src\UniGetUI.PackageEngine.Managers.Chocolatey\choco-cli

      - name: Get build from other job
        uses: actions/download-artifact@v4
        with:
          name: UniGetUI-build-${{ matrix.architecture }}
          path: unigetui_bin
          github-token: ${{ github.token }}
          run-id: ${{ inputs.run_id || github.run_id }}

      - name: Show tree
        run: |
          echo %cd%
          tree

      - name: Build installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
        with:
          path: UniGetUI.iss

      - name: Upload installer as artifact
        uses: actions/upload-artifact@v4
        with:
          name: UniGetUI-Installer-${{ matrix.architecture }}
          path: "UniGetUI Installer.exe"
