run-name: Build UniGetUI
on:
  workflow_dispatch:
jobs:
  BuildForARM64:
    runs-on: windows-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          #architecture: 'x64'
      - name: Clone repo
        uses: actions/checkout@master
        with:
          repository: marticliment/UniGetUI
      - name: Download pip dependencies
        run: | 
          cd UniGetUI
          python3 -m venv .
          #powershell 
          pip install -r requirements.txt
      - name: Build
        run: .\build_release.bat
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: .\
          include-hidden-files: true
