name: Test
run-name: Test
on:
  workflow_dispatch:
      inputs:
        win-x64:
          type: boolean
        win-x86:
          type: boolean
        win-arm64:
          type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        run: echo ${{ toJSON(inputs) }}
