name: Test
run-name: Test
on:
  workflow_dispatch:
      inputs:
        win-x64:
          type: boolean
        win-x86:
          type: boolean
        win-arm64:
          type: boolean

jobs:
  get-selected:
    runs-on: ubuntu-latest
    outputs: # Set this to consume the output on other job
      selected: ${{ steps.get-selected-step.outputs.selected }}
    steps:
      - id: get-selected-step
        uses: joao-zanutto/get-selected@v1.1.1
        with:
          format: json

  build:
    needs: get-selected
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: fromJSON( ${{ needs.get-selected.outputs.selected }} )
    steps:
      - name: Echo inputs
        run: echo ${{ matrix.variant }}
        #run: echo ${{ toJSON(inputs) }}
