name: Test
run-name: Test
on:
  workflow_dispatch:
      inputs:
        win-x64:
          type: boolean
        win-x86:
          type: boolean
        win-arm64:
          type: boolean

jobs:
  get-selected:
    runs-on: ubuntu-latest
    outputs: # Set this to consume the output on other job
      selected: ${{ steps.get-selected-step.outputs.selected }}
    steps:
      - id: get-selected-step
        uses: joao-zanutto/get-selected@v1.1.1

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: |
          echo ${{ toJSON(inputs) }}
          echo ${{ steps.get-selected-step.outputs.selected }}
